name: ZePortalPlugin
main: de.db.ZePortalPlugin
version: 1.1
author: ZeBobbel
description: A plugin for custom, Stargate-like portals.

commands:
  portal:
    description: Main command for the ZePortalPlugin.
    usage: /<command> [help|new|create]