name: ZePortalPlugin
main: de.db.ZePortalPlugin
version: 1.0
author: TheWolfgang3000
description: Ein Plugin für benutzerdefinierte Stargate-ähnliche Portale.

commands:
  portal:
    description: Hauptbefehl für das ZePortalPlugin.
    usage: /<command> [create]